// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { MyApiService } from './my-api.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  storedValue: string = 'bangalore';
  isLoading: boolean = false;
  error: boolean = false;
  temperature: number = 0;
  desc: string = "";
  name: string = "";
  humidity: string = "";
  visibility: number = 0;
  windSpeed: string = "";
  wIcon: string = "";

  constructor(private myApiService: MyApiService) { }

  ngOnInit() {
    this.getWeatherData(this.storedValue);
  }

  getWeatherData = (city: string) => {
    this.isLoading = true;
    this.myApiService.getData(city).subscribe(
      (response) => {
        this.isLoading = false;
        this.temperature = Math.round(response.main.temp - 273.15);
        this.desc = response.weather[0].description;
        this.name = response.name;
        this.humidity = response.main.humidity;
        this.visibility = response.visibility / 1000;
        this.windSpeed = response.wind.speed;
        this.wIcon = response.weather[0].icon;
        setTimeout(() => {
          this.isLoading = false;
        }, 2000);
      },
      (error) => {
        console.error('Error fetching data:', error);
        this.isLoading = false;
        this.error = true;
      }
    );
  };

  onInputChange(e: any) {
    this.storedValue = e.target.value;
  }
}

<div class="App">
  <div class="container">
    <div>
      <h1>Weather App</h1>
    </div>
    <form id="content" autoComplete="off">
      <input type="text" name="input" class="Search-box" (change)="onInputChange($event)" />
      <span></span>
    </form>
    <button class="search_btn" (click)="getWeatherData(storedValue)">
      Search
    </button>
    <div id="card" class="weather">
      <div class='loading_view' *ngIf="isLoading; else weatherBlock">
        <div class="loading">
        </div>
      </div>
      <ng-template #weatherBlock>
        <div *ngIf="!isLoading && !error; else errorBlock">
          <div class="details">
            <div class="temp">
              {{ temperature }}<span>&deg;</span>
            </div>
            <div class="right">
              <div id="summary">{{ desc }}</div>
              <div style="font-weight: bold; margin-top: '4px';">{{ name }}</div>
            </div>
          </div>
          <div class="weather_img_view">
            <img class="weather_img" alt="weather" [src]="'assets/images/' + wIcon + '.svg'" />
          </div>
          <div class="infos">
            <div class="weather_other_details_view">
              <div class="">Humidity - {{ humidity }}%</div>
            </div>
            <div class="weather_other_details_view">
              <div class="">Visibility - {{ visibility }} km</div>
            </div>
            <div class="weather_other_details_view">
              <div class="">Wind Speed - {{ windSpeed }} km</div>
            </div>
          </div>
        </div>
      </ng-template>
      <ng-template #errorBlock>
        <div class='not_found'>
          Not Found !!!
        </div>
      </ng-template>
    </div>
  </div>
</div>

// react/src/App.js
import React, { useEffect, useState } from 'react';
import axios from "axios";
import './App.css';

const App = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(false);
  const [temperature, setTemperature] = useState("");
  const [city, setCity] = useState("bangalore");
  const [desc, setDesc] = useState("");
  const [name, setName] = useState("");
  const [humidity, setHumidity] = useState("");
  const [visibility, setVisibility] = useState("");
  const [windspeed, setWineSpeed] = useState("");
  const [wicon, setWicon] = useState("");

  useEffect(() => {
    window.process = {
      ...window.process,
    };
    getWeatherData();    
  }, [])

  const getWeatherData = () => {
    const { REACT_APP_API_URL } = process && process?.env;
    if (REACT_APP_API_URL) {
      setIsLoading(true);
      axios({
        method: "GET",
        url: `${REACT_APP_API_URL}/getWeatherInfo/city?city=${city}`
      })
        .then((response) => {
          setTemperature(Math.round(response.data.main.temp - 273.15));
          setDesc(response.data.weather[0].description);
          setName(response.data.name);
          setHumidity(response.data.main.humidity);
          setVisibility(response.data.visibility / 1000);
          setWineSpeed(response.data.wind.speed);
          setWicon(response.data.weather[0].icon);
          console.log(response);
          setTimeout(() => {
            setIsLoading(false);
          }, 2000);
        })
        .catch((error) => {
          setIsLoading(false);
          setError(true);
        });
    }
  };

  return (
    <div className="App">
      <div className="container">
        <div>
          <h1>Weather APP</h1>
        </div>
        <form id="content" autoComplete="off">
          <input
            type="text"
            name="input"
            className="Search-box"
            onChange={(e) => setCity(e.target.value)}
          />
          <span></span>
        </form>
        <button
          className="search_btn"
          onClick={() => {
            getWeatherData(city);
          }}
        >
          Search
        </button>
        <div id="card" className="weather">
          {isLoading ? (
            <div className='loading_view'>
              <div className="loading" />
            </div>
          ) : (
            !error ? (
              <>
                <div className="details">
                  <div className="temp">
                    {temperature}
                    <span>&deg;</span>
                  </div>
                  <div className="right">
                    <div id="summary">{desc}</div>
                    <div style={{ fontWeight: "bold", marginTop: "4px" }}>{name}</div>
                  </div>
                </div>
                <img className="weather_img" alt="image1" src={`${wicon}.svg`} />
                <div className="infos">
                  <img
                    alt="humidity1"
                    className="humidity_img"
                    style={{ width: "5", height: "5" }}
                    src="humidity.svg"
                  ></img>
                  <div className="humidity">Humidity {humidity}%</div>
                  <img
                    alt="visibility1"
                    className="visibility_img"
                    style={{ width: "5", height: "5" }}
                    src="visibility.svg"
                  ></img>
                  <div className="visibility">Visibility {visibility} km</div>
                  <img
                    alt="wind_speed1"
                    className="wind_img"
                    style={{ width: "5", height: "5" }}
                    src="wind.svg"
                  ></img>
                  <div className="wind_speed">Wind Speed {windspeed} km</div>
                </div>
              </>
            ) : (
              <div className='notfound'>
                Not Found !!!
              </div>
            )
          )}
        </div>
      </div>
    </div >
  );
}

export default App;
